config/routes.rb
Rails.application.routes.draw do

  root to: "task#index", via: :get
  resources :task

  post "task/new", :controller => 'task', :action => 'create'
  get "task/:id/edit", :controller => 'task', :action => 'edit'
  post "task/:id/edit", :controller => 'task', :action => 'update'
  post "task/:id/destroy", :controller => 'task', :action => 'delete'


end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
	def index
		@tasks = Task.all
	end

	def edit
		@task = Task.find(params[:id])
	end

	def new
	end

	def update
	  task = Task.find(params[:id])
	  task.update_attributes(task_params)
      redirect_to :root
    end

	def create
		@task = Task.new(task_params)
		if @task.save
			redirect_to :root, notice: 'Your task was successfully posted!'
		else
			redirect_to :back, notice: 'Your task was unsuccessfully posted!'
		end
	end

	def destroy
		task = Task.find(params[:id])
		task.destroy
		redirect_to :root, notice: 'Your task was successfully deleted!'
	end

	private

	def task_params
		params.require(:task).permit(:name, :description, :due)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Planner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Baloo+Bhaina" rel="stylesheet">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/task/edit.html.erb
<div class='form-container'>
<div class='form'>
<%= form_for @task do |f| %>
  <div class='form-field'>
    Name: <%= f.text_field :name, class: 'form-box'%>
    </div>
    <div class='form-field'>
    Description : <%= f.text_area :description, class: 'form-box' %>
    </div>
    <div class='form-field'>
    Due : <%= f.number_field :due, class: 'form-box' %>
    </div>
    <span class='form-field'>
    <%= f.submit 'Save Task', class: 'link-button' %>
    </span>
<% end %>
</div>
</div>

app/views/task/index.html.erb
<% @tasks.each do |task| %>
	<div class='task-item'>
		<div class='task-name'>
			<%= task.name %>
		</div>
		<div class='task-description'>
			<%= task.description %>
		</div>
		<div class='task-due'>
			<%= task.due %>
		</div>
		<div class='task-options'>
			<%= link_to "Edit", edit_task_path(id: task.id), method: :get, class: 'link-button' %>
			<%= link_to "Destroy", task_path(id: task.id), method: :delete, data: { confirm: "You sure you wanna delete this task?" }, class: 'link-button' %>
		</div>
	</div>
<% end %>

</br>

<%= link_to "Create New Task", new_task_path, class: 'task-create' %>

app/views/task/new.html.erb
<div class='form-container'>
<div class='form'>
<%= form_for :task do |f| %>
	<div class='form-field'>
    Name: <%= f.text_field :name, class: 'form-box'%>
    </div>
    <div class='form-field'>
    Description : <%= f.text_area :description, class: 'form-box' %>
    </div>
    <div class='form-field'>
    Due : <%= f.number_field :due, class: 'form-box' %>
    </div>
    <span class='form-field'>
    <%= f.submit 'Save Task', class: 'link-button' %>
    </span>
<% end %>
</div>
</div>